trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'MicoRegistery'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'MicoRegistery'
    command: 'login'

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'mico-arm'
    appName: 'mappi-backend'
    containers: 'micoregistery.azurecr.io/vhlahtiokp2_app:latest'