# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

  # perform unit-tets and publish test and code coverage results
  - script: |
      cd OKP-2-frontend
      npm install && npm rebuild
      npx ng test --no-watch
    displayName: "Perform unit tests"
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/testresults/TESTS-*.xml"
      failTaskOnFailedTests: true
      testRunTitle: "Publish unit test results"
