version: '3.9'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - '5432:5432'
    volumes:
      - ${WEBAPP_STORAGE_HOME:-}db:/var/lib/postgresql/data
      - ${WEBAPP_STORAGE_HOME:-.}/db.sql:/docker-entrypoint-initdb.d/db.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 5433:8080

  app:
    build: .
    ports:
      - ${WEBSITES_PORT:-7266}:7266 # Use the WEBSITES_PORT variable in the port mapping
    environment:
      DB_HOST: db
      JWT_SECRET: aGVsbG8gd29ybGQ= # Development (not very secret) secret
      WEBSITES_PORT: 7266 # Set the port for the WebApp
    depends_on:
      - db

volumes:
  db:
    driver: local
